name: review

on:
  pull_request:

jobs:
  plan:
    uses: ./.github/workflows/plan.yml
    with:
      env: lz
      project: bootstrap
      stack: tfstate
    secrets:
      org_id: ${{ secrets.org_id }}
      billing_account: ${{ secrets.billing_account }}
