name: review

on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/plan.yml
        with:
          env: lz
          project: bootstrap
          stack: tfstate
