name: review

on:
  pull_request:

jobs:
  bootstrap:
    uses: ./.github/workflows/plan.yml
    with:
      env: lz
    secrets:
      org_id: ${{ secrets.org_id }}
      billing_account: ${{ secrets.billing_account }}

  management:
    uses: ./.github/workflows/plan.yml
    with:
      env: lz
      path: management

  artifacts:
    uses: ./.github/workflows/plan.yml
    with:
      env: lz
      path: artifacts

  cloudrun-simple:
    uses: ./.github/workflows/plan.yml
    with:
      env: dev
      path: cloudrun-simple
      check-cost: true
    secrets:
      infracost_api_key: ${{ secrets.infracost_api_key }}
